_wandb:
    value:
        cli_version: 0.22.2
        e:
            b515zuv72mwad9v581c8qs72xgjxdfc1:
                codePath: data_scarcity.py
                codePathLocal: data_scarcity.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "2014574526464"
                        used: "466940043264"
                email: victor.gialis@gmail.com
                executable: /home/ngrotus/CWRU_MAE/.venv/bin/python
                git:
                    commit: 118c5893f9b6fb3714842913fea078930d574e4b
                    remote: https://github.com/Victor-Gialis/CWRU_MAE.git
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-c31c768b-e104-c884-f3ab-abff4abe397e
                host: pclinux-ngs
                memory:
                    total: "33337475072"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/ngrotus/CWRU_MAE/data_scarcity.py
                python: CPython 3.12.9
                root: /home/ngrotus/CWRU_MAE
                startedAt: "2025-11-06T15:14:27.971624Z"
                writerId: b515zuv72mwad9v581c8qs72xgjxdfc1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 51
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.9
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
