_wandb:
    value:
        cli_version: 0.22.2
        e:
            d2cnke69g1cs2a9e0nd6ibx2cszu0y78:
                codePath: scripts/pretrain_optimisation.py
                codePathLocal: scripts/pretrain_optimisation.py
                email: victor.gialis@gmail.com
                executable: /home/ngrotus/CWRU_MAE/.venv/bin/python
                git:
                    commit: 6669623b6279ddf89dc3fe7fd5cb8ae43ea93140
                    remote: https://github.com/Victor-Gialis/CWRU_MAE.git
                host: pclinux-ngs
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/ngrotus/CWRU_MAE/scripts/pretrain_optimisation.py
                python: CPython 3.12.9
                root: /home/ngrotus/CWRU_MAE
                startedAt: "2025-10-23T16:04:36.451631Z"
                writerId: d2cnke69g1cs2a9e0nd6ibx2cszu0y78
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 35
                - 51
            "2":
                - 1
                - 35
                - 51
            "3":
                - 2
                - 17
            "4": 3.12.9
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
direction:
    value:
        - MINIMIZE
