_wandb:
    value:
        cli_version: 0.22.2
        e:
            1igc8kltnmbdj7kugbzvjprvlkx5m8td:
                codePath: scripts/pretrain_optimisation.py
                codePathLocal: scripts/pretrain_optimisation.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "2014574526464"
                        used: "466961235968"
                email: victor.gialis@gmail.com
                executable: /home/ngrotus/CWRU_MAE/.venv/bin/python
                git:
                    commit: 6669623b6279ddf89dc3fe7fd5cb8ae43ea93140
                    remote: https://github.com/Victor-Gialis/CWRU_MAE.git
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-c31c768b-e104-c884-f3ab-abff4abe397e
                host: pclinux-ngs
                memory:
                    total: "33337475072"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/ngrotus/CWRU_MAE/scripts/pretrain_optimisation.py
                python: CPython 3.12.9
                root: /home/ngrotus/CWRU_MAE
                startedAt: "2025-10-23T13:36:47.045471Z"
                writerId: 1igc8kltnmbdj7kugbzvjprvlkx5m8td
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 35
                - 51
            "2":
                - 1
                - 35
                - 51
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
