_wandb:
    value:
        cli_version: 0.22.2
        e:
            h5lj224rp2hdd5hgb7qum4raj0bgmlry:
                codePath: scripts/pretrain.py
                codePathLocal: scripts/pretrain.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "2014574526464"
                        used: "467192438784"
                email: victor.gialis@gmail.com
                executable: /home/ngrotus/CWRU_MAE/.venv/bin/python
                git:
                    commit: 6669623b6279ddf89dc3fe7fd5cb8ae43ea93140
                    remote: https://github.com/Victor-Gialis/CWRU_MAE.git
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-c31c768b-e104-c884-f3ab-abff4abe397e
                host: pclinux-ngs
                memory:
                    total: "33337475072"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/ngrotus/CWRU_MAE/scripts/pretrain.py
                python: CPython 3.12.9
                root: /home/ngrotus/CWRU_MAE
                startedAt: "2025-10-24T09:39:37.169776Z"
                writerId: h5lj224rp2hdd5hgb7qum4raj0bgmlry
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 51
            "2":
                - 1
                - 51
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
dataloader:
    value:
        batch_size: 64
        shuffle: true
dataset:
    value:
        downsample_factor: 2
        fault_filter: null
        name: CWRU
        pretext_task: flip
        speed_filter: null
        stride: 256
        transform_type: psd
        window_size: 2048
model:
    value:
        decoder_dim: 512
        dropout: 0.2565
        encoder_dim: 512
        heads: 8
        n_layers: 3
        patch_size: 16
training:
    value:
        epochs: 100
        learning_rate: 0.0003695
        model_name: model_v5.1
        normalization: log
        weight_decay: 1.1133e-05
