_wandb:
    value:
        cli_version: 0.22.2
        e:
            m7iyfr5s3b79x08k0zwli6gzkau5siwi:
                codePath: pretrain.py
                codePathLocal: pretrain.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "2014574526464"
                        used: "476960780288"
                email: victor.gialis@gmail.com
                executable: /home/ngrotus/CWRU_MAE/.venv/bin/python
                git:
                    commit: 382c2a9d9a8b26b76d13e114fe354239af7ded03
                    remote: https://github.com/Victor-Gialis/CWRU_MAE.git
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-c31c768b-e104-c884-f3ab-abff4abe397e
                host: pclinux-ngs
                memory:
                    total: "33337470976"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/ngrotus/CWRU_MAE/pretrain.py
                python: CPython 3.12.9
                root: /home/ngrotus/CWRU_MAE
                startedAt: "2026-01-05T14:42:03.928516Z"
                writerId: m7iyfr5s3b79x08k0zwli6gzkau5siwi
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 51
            "2":
                - 1
                - 51
            "3":
                - 2
                - 13
                - 61
            "4": 3.12.9
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
